name: app_environment
channels:
  - snowflake
  - conda-forge
  - defaults
dependencies:
  - python=3.11.*
  - numpy=2.2.4
  - pandas=2.2.0
  - plotly=6.0.1
  - pypdf=4.2.0
  - pdfplumber=0.11.4
  - python-dotenv=0.21.0
  - scikit-learn=1.6.1
  - streamlit=1.32.0
  - snowflake-snowpark-python=1.5.0
  - snowflake-connector-python=3.5.0
  - pillow=10.2.0  # PDF画像処理用
  - xlsxwriter=3.1.9  # Excelエクスポート用
  - reportlab=4.1.0  # PDFエクスポート用
  - pip:
    - openai>=1.12.0  # AI機能用
    - langchain>=0.1.0  # AI機能用
    - sentence-transformers>=2.5.1  # テキスト埋め込み用 